import { readFileSync } from 'node:fs';
import { join } from 'node:path';
// Contract test: every document the export writes must be readable by the
// domain. Runs against the real public/data, regenerated by `npm test`.
import { describe, expect, it } from 'vitest';
import { Catalogue } from '../application/catalogue';
import { LANGS } from '../application/lang';
import type { ResumeDocument } from '../domain/resume';

const read = (lang: string): ResumeDocument =>
  JSON.parse(readFileSync(join(process.cwd(), 'public/data', `${lang}.json`), 'utf8'));

describe.each(LANGS)('exported %s document', (lang) => {
  it('builds a catalogue without a dangling reference or unreadable date', () => {
    expect(() => Catalogue.from(read(lang))).not.toThrow();
  });

  it('keeps the same entry ids as English, so a page exists in every language', () => {
    const ids = (l: string) => Catalogue.from(read(l)).entries.map((e) => e.id);
    expect(ids(lang)).toEqual(ids('en'));
  });
});
