// The shipped PDFs must actually carry the document properties, not merely be
// generated by code that knows how to write them: the .xmpdata file is picked
// up by pdfx at compile time, so a rename of the temp file or a lost copy step
// would leave the pipeline green and the artefacts anonymous again.
//
// PDF/A keeps the XMP packet uncompressed, so it is read here as plain text —
// no pdfinfo, no external tool, nothing for CI to miss.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { LANGS, OUTPUT_DIR } = require('./pdf/config');
const I18N = require('./pdf/i18n');
const { loadResume } = require('./pdf/data');
const { XMP_LANGUAGE } = require('./pdf/metadata');

const xmpOf = (lang) => {
  const buf = fs.readFileSync(path.join(OUTPUT_DIR, `cv_grosjean_baptiste_${lang}.pdf`), 'latin1');
  const packets = buf.match(/<x:xmpmeta[\s\S]*?<\/x:xmpmeta>/g) || [];
  return Buffer.from(packets.join('\n'), 'latin1').toString('utf8');
};
const dc = (xmp, tag) => {
  const m = new RegExp(`<dc:${tag}>[\\s\\S]*?<rdf:li[^>]*>([\\s\\S]*?)</rdf:li>`).exec(xmp);
  return m ? m[1].trim() : null;
};

for (const lang of LANGS) {
  const xmp = xmpOf(lang);
  const t = I18N[lang];
  const b = loadResume(lang).basics;

  test(`${lang}: the PDF's title names the person and the document`, () => {
    assert.equal(dc(xmp, 'title'), `${b.name} — ${t.curriculumVitae}`);
  });

  test(`${lang}: the PDF's author is set, so no reader falls back to the file name`, () => {
    assert.equal(dc(xmp, 'creator'), b.name);
  });

  test(`${lang}: the PDF's subject is the localized professional label`, () => {
    assert.equal(dc(xmp, 'description'), b.label);
  });

  test(`${lang}: the PDF declares its language`, () => {
    assert.equal(dc(xmp, 'language'), XMP_LANGUAGE[lang]);
  });

  test(`${lang}: the PDF carries technical keywords for an ATS`, () => {
    assert.match(xmp, /<dc:subject>[\s\S]*?<rdf:li>SQL<\/rdf:li>/);
  });
}
