// Guard for the UMons volunteering end dates.
//
// Both UMons roles (student representative, TandeMons buddy) ran open-ended
// until 2026-09-04. Five artefacts have to agree that they are over, and only
// two of them are hand-edited:
//
//   1. dsl/resume.grosjean          — the single source of truth (hand-edited).
//   2. assets/data/resume.json      — compiled by dsl/compile.py.
//   3. the six index.html pages     — generated by generate-from-resume.js,
//   4. the fourteen XML mirrors     — likewise, read by the XSLT themes.
//   5. llms-full.txt                — hand-maintained digest, generated by
//                                     nothing, so it drifts unnoticed.
//
// Why this is asserted here rather than left to .github/workflows/dsl.yml:
// that workflow does check assets/data against a fresh compile, but only
// `on: paths: [dsl/**]`. Close a role in resume.json alone and the gate never
// fires, the change merges green, and the next DSL compile silently reverts it
// — which is exactly what happened while writing this. The test suite runs
// with no paths filter, so the agreement is checked from either side.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const { ROOT, LANGS, langOutFile } = require('./config');

const UMONS_END_DATE = '2026-09-04';
const DATA_DIR = path.join(ROOT, 'assets/data');
const read = (...p) => fs.readFileSync(path.join(ROOT, ...p), 'utf8');

// The DSL nests one brace-delimited entry per role inside `volunteer { … }`,
// and spells an open end as the keyword `present` (see dsl/grammar.lark).
function dslUmonsPeriods() {
  const block = read('dsl/resume.grosjean').match(/\n {4}volunteer \{\n([\s\S]*?)\n {4}\}\n/);
  assert.ok(block, 'no volunteer block found in dsl/resume.grosjean');
  const entries = block[1].match(/^ {8}\w+ \{$[\s\S]*?^ {8}\}$/gm) || [];
  return entries
    .filter((e) => /organization "UMons"/.test(e))
    .map((e) => e.match(/period\s+(\S+)/)?.[1]);
}

// The embedded list renders "<li><strong>role</strong> — start – end</li>", and
// an open-ended role puts the literal "Present" in the end slot (untranslated,
// in every language — see renderEmbeddedVolunteer). The work header instead
// emits <time>Present</time>, so this shape is specific to volunteering.
const ONGOING_VOLUNTEER_LINE = /–\s*Present<\/li>/;

const umonsItemsIn = (xml) =>
  xml.match(/<volunteer-item>\s*<organization>UMons<\/organization>[\s\S]*?<\/volunteer-item>/g) ||
  [];

test('the DSL closes both UMons volunteer periods', () => {
  const periods = dslUmonsPeriods();
  assert.equal(periods.length, 2);
  for (const period of periods) {
    assert.ok(period?.endsWith(`..${UMONS_END_DATE}`), `period is still "${period}"`);
  }
});

test('the compiled resume.json carries the same end date', () => {
  const roles = JSON.parse(read('assets/data/resume.json')).volunteer.filter(
    (v) => v.organization === 'UMons',
  );
  assert.equal(roles.length, 2);
  for (const role of roles) {
    assert.equal(role.endDate, UMONS_END_DATE, `${role.position} carries no end date`);
  }
});

test('no generated page still lists a volunteer role as ongoing', () => {
  for (const lang of LANGS) {
    const html = fs.readFileSync(langOutFile(lang), 'utf8');
    assert.doesNotMatch(html, ONGOING_VOLUNTEER_LINE, `${lang} page is stale`);
  }
});

test('every XML mirror carries the UMons end date', () => {
  const mirrors = fs.readdirSync(DATA_DIR).filter((f) => /^resume.*\.xml$/.test(f));
  assert.ok(mirrors.length >= LANGS.length, `only ${mirrors.length} mirrors found`);
  for (const file of mirrors) {
    const items = umonsItemsIn(fs.readFileSync(path.join(DATA_DIR, file), 'utf8'));
    assert.equal(items.length, 2, `${file} holds ${items.length} UMons roles`);
    for (const item of items) {
      assert.match(item, new RegExp(`<endDate>${UMONS_END_DATE}</endDate>`), `${file} is stale`);
    }
  }
});

test('the llms-full.txt digest agrees about the UMons roles', () => {
  const lines = read('llms-full.txt')
    .split('\n')
    .filter((l) => l.startsWith('- **') && l.includes('UMons ('));
  assert.equal(lines.length, 2, `found ${lines.length} UMons volunteer lines`);
  for (const line of lines) {
    assert.match(line, new RegExp(`${UMONS_END_DATE}\\)$`), `stale digest line: ${line}`);
  }
});
